### ISSUE TITLE
FXBlurView not blurring on iOS 11

### ISSUE THREAD

**Issue by Suryu** [Orderella/PopupDialog#181] opened 2017-11-10 14:39 UTC
# Report
Background blur does not work on iOS 11 (tested with liveBlur disabled)

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): 10.12.6
- Xcode version (e.g. 8.0): 9.1
- PopupDialog version (e.g. 0.5.0): 0.6.0
- Minimum deployment target (e.g. 9.0): 10.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 4.1

## Dependency management

- Dependency manager (e.g. CocoaPods): Carthage
- Version (e.g. 1.1.0): 0.26.2

## What did you do?
Present some dialogs we have in our app using PopupDialog

## What did you expect to happen?
The dialog did blur the background on iOS 10

## What happened instead?
Background was not blurred on iOS 11.1

**Comment by mwfire** [comment] 2017-11-10 21:14
Hey there! Can you confirm the example project works for you? I cannot reproduce this for any iOS up to 11.1. Can you share your code?

**Comment by mwfire** [comment] 2017-11-16 15:51
Hey @Suryu, any updates here? Otherwise I will close this...

**Comment by Suryu** [comment] 2017-11-16 23:58
Hi, sorry for the delay. I will check this on sample project and will try to track down what could be the problem.

**Closed as completed** 2017-11-30 23:05 UTC
Labels: awaiting-feedback
