### ISSUE TITLE
Crash when present a popup which inited by a View Controller

### ISSUE THREAD

**Issue by thuongdao** [Orderella/PopupDialog#282] opened 2018-10-11 03:07 UTC
## Environment
My development environment

- Xcode version (e.g. 9.1): 9.4.1
- PopupDialog version (e.g. 0.5.0): 0.7.1 , 0.8.1
- Language Swift 4.1

## Pices of Code 
``
        let dialog = PopupDialog(viewController: confirmVC,
                                 buttonAlignment: .vertical,
                                 transitionStyle: .bounceUp,
                                 gestureDismissal: false,
                                 completion: nil)
``
``
        present(dialog, animated: true, completion: nil)
``

**Comment by mwfire** [comment] 2018-10-11 05:32
Hi there, please also paste the error message and stack trace here.

Thanks!

**Comment by thuongdao** [comment] 2018-10-11 10:30
Thanks for quick response
![screen shot 2018-10-11 at 17 27 44](https://user-images.githubusercontent.com/4618162/46798089-1e6e0b80-cd7b-11e8-8fb2-167cc2de7da1.png)
![screen shot 2018-10-11 at 17 27 25](https://user-images.githubusercontent.com/4618162/46798099-27f77380-cd7b-11e8-9382-9d2b17f4b4f8.png)

as you could see, crash cause by DynamicBlurView library

**Comment by adarhef** [comment] 2018-11-05 15:06
I have the same crash.

**Comment by mwfire** [comment] 2018-11-05 20:21
Hey guys, so far I had no luck with reproducing this. Could you please provide an example project showcasing the issue and share it here? Thanks a lot!

**Comment by adarhef** [comment] 2018-11-06 09:28
Ignore this "fix" for now, looks like it doesn't work yet. I was under the impression that it does until I pulled the fork and it made the screen go black instead of blurring it. Not crashing is a nice bonus though. :)

**Comment by adarhef** [comment] 2018-11-06 13:46
Alright, I give up.
I cloned my BlurView fork and referenced it locally from my app's Podfile but it wasn't picking up the changes until I performed a clean build, which takes prohibitively long. I can't actually debug this properly at the moment.
It's unfortunate because this crash reproduced at some parts of my app, but not in others, and when it did reproduce it did so very reliably.
I had to revert to PopupDialog 0.7.1 and DynamicBlurView 2.0.2 (commit c1f9c69, need Swift 4.2 support).
@thuongdao , if you need a working setup for Swift 4.2 (albeit without the pretty blur effect of the new versions), check out my forks at [](https://github.com/zeekit).

**Comment by thuongdao** [comment] 2018-11-07 07:37
@adarhef thanks for fixing it,

but I could not see your forks at

**Comment by adarhef** [comment] 2018-11-07 10:38
Sorry, I didn't notice my previous comment didn't parse the link.
Here's PopupDialog: [https://github.com/zeekit/PopupDialog]()
And [https://github.com/zeekit/DynamicBlurView](), c1f9c69. Come to think of it I don't think you need my fork for DynamicBlurView, just use the original repo with the same commit.

**Comment by ergunkocak** [comment] 2018-12-02 16:15
Hi @adarhef ,

Is your fix working? If so, is it merged to here?

Best

**Comment by adarhef** [comment] 2018-12-02 20:54
Not merged and not fixed unfortunately. Have given up on it.

**Comment by mwfire** [comment] 2018-12-02 21:00
Unfortunately, I cannot merge DynamicBlurView fixes here. They will be overwritten, as it is an external dependency. Any fixes have to be merged to the original repository. However, I tried and I am not able to reproduce this. Please attach an example project showcasing the issue.

**Comment by ergunkocak** [comment] 2018-12-03 13:17
I experienced the exact same problem as @thuongdao 
In my case i tried to display popup when there is already a presented viewController with an Apple blur background

**Comment by sgbasaraner** [comment] 2019-01-08 14:24
@thuongdao @ergunkocak does this crash occur even when the blur features are disabled?

**Comment by mkelitz** [comment] 2019-01-15 07:54
Same issue here. Any Fix?

**Comment by sgbasaraner** [comment] 2019-01-15 08:13
@mkelitz are you using blur in your popups?

**Comment by mkelitz** [comment] 2019-01-15 08:18
@sgbasaraner  Yes

**Comment by sgbasaraner** [comment] 2019-01-15 08:19
@mkelitz is this on prod? can you please test it without blur if it's feasible?

**Comment by mkelitz** [comment] 2019-01-15 08:21
Do you mean by changing
"overlayAppearance.blurEnabled = true"
to
"overlayAppearance.blurEnabled = false"
on AppDelegate?

Yes, tried and same issue.

**Comment by sgbasaraner** [comment] 2019-01-15 08:25
@mkelitz also liveBlurEnabled, I suspect that might be causing it but not sure

**Comment by mkelitz** [comment] 2019-01-15 08:29
@sgbasaraner Also changed liveBlur = false (although it is deprecated, but just in case) and same error.

**Comment by mkelitz** [comment] 2019-01-15 08:30
@sgbasaraner I mean both liveBlur and liveBlurEnabled are set to false

**Comment by sgbasaraner** [comment] 2019-01-15 08:31
@mkelitz Interesting, I have the same setup but never experienced a crash. Does it happen 100% of the time?

**Comment by mkelitz** [comment] 2019-01-15 08:33
@sgbasaraner Since I upgraded to swift 4.2 with latest PopupDialog yes, it happens all the time.

**Comment by mwfire** [comment] 2019-01-15 16:10
Hi @sgbasaraner, would it be possible to provide an example project showcasing this issue? Thx a lot!

**Comment by sgbasaraner** [comment] 2019-01-16 07:58
Hi @mwfire, I am not experiencing this issue myself, I'm just trying to decide on whether or not to use PopupDialog in prod. I'm interested in resolving this issue, but I was unable to recreate the crash.

**Comment by adarshjayan7574** [comment] 2019-01-21 06:47
Still i am facing the same issue. Is there any workaround or fix ??

**Comment by mkelitz** [comment] 2019-01-21 08:15
@adarshjayan7574 For what I've learned so far, I have the issue if the popup is opened right after the app is launched (any other pop used in any other app flow works just fine), so my fix was simply to launch the popup (a push permission popup in my case) in a later moment. Not a very elegant fix but working.
Good luck

**Comment by adarshjayan7574** [comment] 2019-01-21 09:20
Thank you @mkelitz  for the reply but your solution is not working in my case, so i  removed blurView (commented addSubview(blurView) in  PopupDialogOverlayView.swift )and now it seems to be working fine.

**Comment by stanley4429** [comment] 2019-02-21 07:43
I can't face the issue when using the Simulators.But It's very easy to see the crash in iPhone XR devices.

**Closed as completed** 2019-04-01 04:07 UTC
Labels: wontfix

**Comment by ehizokhai** [comment] 2020-03-10 22:39
Any fix for this issue.  Experiencing same problem on OS 13
