### ISSUE TITLE
Custom popupDialog breaks when VC is presented above it

### ISSUE THREAD

**Issue by otymartin** [Orderella/PopupDialog#38] opened 2016-09-19 04:03 UTC
@mwfire 
I copied the custom xib from the example and place it in my project. I removed all the stuff in it and replaced it with a `tableView` displaying my contact list. It works perfectly at this point. When a `cell accessory` is tapped, I present the `MFMessageComposeViewController`. When that gets dismissed, my popup dialogue completely breaks. Here are the photos in action sequence.

What could it be?😂

<img width="304" alt="screen shot 2016-09-18 at 11 59 11 pm" src="https://cloud.githubusercontent.com/assets/2222881/18622378/5c82611c-7dfc-11e6-9d91-8d107a01633f.png">
<img width="305" alt="screen shot 2016-09-18 at 11 59 38 pm" src="https://cloud.githubusercontent.com/assets/2222881/18622379/5f687cc2-7dfc-11e6-9d86-ba4e70431887.png">

I noticed that as the `MessagesComposeViewController` is being presented, popup dialogue is pushed to the top left.
<img width="311" alt="screen shot 2016-09-18 at 11 59 47 pm" src="https://cloud.githubusercontent.com/assets/2222881/18622380/60e9621e-7dfc-11e6-9983-a4b7ca00d720.png">
<img width="303" alt="screen shot 2016-09-19 at 12 00 04 am" src="https://cloud.githubusercontent.com/assets/2222881/18622398/9c7eb004-7dfc-11e6-9109-3c7767ddbe59.png">

**Comment by mwfire** [comment] 2016-09-19 08:48
Thanks for reporting this, I'll check that out.

**Comment by mwfire** [comment] 2016-09-22 17:20
Hm, I can't reproduce it so far. Are you presenting the view controller on a navigation view controller?
You could also try presenting it on the popup itself, if you are not already doing this, like:

```
popup.present(myViewController, animated: true, completion: nil)
```

**Comment by otymartin** [comment] 2016-09-22 18:16
@mwfire 
No its not in a navgiation controller. the view controller being presented above the popup dialogue is the `MessageComposeViewController`. unfortunately, I have no control over its presentation.

Is that possible? Presenting the messages compose VC inside the popup itself?

**Comment by mwfire** [comment] 2016-09-22 18:34
It's definitely possible, as PopupDialog is just a view controller by itself. I have not investigated side effects yet, though. So the following _should_ work:

```
let composeVC = MFMailComposeViewController()
// ...

// Present the view controller modally.
popup.present(composeVC, animated: true, completion: nil)
```
- Swift3

**Comment by otymartin** [comment] 2016-09-22 19:56
@mwfire Ok Im trying this again soon then will post the result 👍

**Comment by leizard** [comment] 2016-10-04 05:09
Hi @otymartin. I'm implementing the same thing but my tableview never appears. Could you help me on that ?
I put the tableview inside the xib View:

<img width="632" alt="screen shot 2016-10-04 at 12 06 43" src="https://cloud.githubusercontent.com/assets/5291692/19063242/25bb5c48-8a2b-11e6-99fa-9b66fe4f8d1e.png">

Then in the xib view controller:

```
import UIKit
import M13Checkbox

class FilterPopupPrice: UIViewController {

    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var filterTableView: UITableView!

    override func viewDidLoad() {
        super.viewDidLoad()

        filterTableView.dataSource = self
        filterTableView.delegate = self
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
}

extension FilterPopupPrice: UITableViewDataSource, UITableViewDelegate {

    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 3
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = Bundle.main.loadNibNamed("FilterTableViewCell", owner: self, options: nil)?.first as! FilterTableViewCell

        cell.filterLabel.text = "test"
        cell.filterCheckbox.setCheckState(M13Checkbox.CheckState.checked, animated: false)

        return cell
    }
}
```

When I show the popup, this is the result

<img width="352" alt="screen shot 2016-10-04 at 12 07 58" src="https://cloud.githubusercontent.com/assets/5291692/19063253/4cde1e3c-8a2b-11e6-9344-41483c49deba.png">

Did I miss something ?
Thank you.

**Comment by otymartin** [comment] 2016-10-04 05:21
@leizard if I remember correctly this had to do with auto layout specifically, setting constraints for width and height on the tableview.
Thank should be it.

**Comment by leizard** [comment] 2016-10-04 05:29
I think I did right with auto layout. It just has space = 0 on four sides and should stretch according to the main view size. The thing is when I debug like this:
<img width="783" alt="screen shot 2016-10-04 at 12 25 38" src="https://cloud.githubusercontent.com/assets/5291692/19063520/e1f45e8a-8a2d-11e6-860e-6c20489a6e01.png">
It never runs into `cellForRowAt` and stuck running three times at `numberOfRowsInSection` although I set `numberOfSections` = 1. That is weird.
Do you have any idea ?

**Comment by otymartin** [comment] 2016-10-04 05:30
@leizard you need to set specific width and height constraints. the `space 0 up down left right` thing wont do it i dont think

Question: Why are you hardcoding `numberOfRowsInSection?` it should be `dataSource.count`

**Comment by leizard** [comment] 2016-10-04 05:49
I hardcode `numberOfRowsInSection` for test reason.
I set the width and height constraints and it did work. Woa..
So how could we have a tableview with dynamic height according to number of table cell ?

**Comment by otymartin** [comment] 2016-10-04 08:44
@leizard Good question :) I haven't thought of it yet. I still have to get back to figuring out how to solve my original issue.

But off the top of my head, I planned on keeping the tableview fixed at 300points width regardless of device so its never smaller or bigger than that.

**Comment by leizard** [comment] 2016-10-04 08:55
@otymartin . I think it is not the big problem. anw, thank you for helping me solve my issue :)

**Comment by leizard** [comment] 2016-10-04 09:02
Another question if you don't mind. Do you implement `didSelectRowAt indexPath`. I implement `didSelectRowAt` but it never fires. The row is not clickable but if you long tap, it seem clicked. I think it relates with this gesture issue [here](http://stackoverflow.com/questions/18159147/iphone-didselectrowatindexpath-only-being-called-after-long-press-on-custom-c), but still no clue where I should remove the tap gesture recogniser which is mentioned

**Comment by leizard** [comment] 2016-10-04 09:11
I think @mwfire could help with this gesture problem :)

**Comment by otymartin** [comment] 2016-10-04 09:14
@leizard its defnintley the gesture. i scratched my head too trying to figure these things out but i eventually pull through :)

``` swift
  // Create the dialog
     let popup = PopupDialog(viewController: inviteViewController, transitionStyle: .BounceUp, buttonAlignment: .Horizontal, gestureDismissal: false)
```

**Comment by leizard** [comment] 2016-10-04 09:24
Yeah.. I had a glance of it but I wanted to keep the "click outside to close" feature so I don't touch it. So I guess we have to trade off in this case.
Thank you again @otymartin

**Comment by otymartin** [comment] 2016-10-04 11:51
@leizard yea i had to make that tradeoff too. unless @mwfire has a better solution

**Comment by mwfire** [comment] 2016-10-05 17:58
Heya everyone! Yeah, gestureDismissal should not really also be the flag for clicking outside.
In future versions, this should be an option set. I just did not want to break current API while moving to Swift 3, that would be too confusing.

**Comment by AgapovOne** [comment] 2016-10-28 10:03
Yes, I can confirm that there are problems with gesture dismissal when a table view is used. Cannot correctly click on a row. So after removing this gestureDismissal, it worked fine.

btw, thx for the lib.

**Closed as completed** 2016-12-31 10:28 UTC

**Comment by Bilal10Akram** [comment] 2018-06-28 08:54
@otymartin can you please tell me how you gave  dynamic height to your tableview???

**Comment by otymartin** [comment] 2018-06-28 18:45
@Bilal10Akram To be honest that was a long time ago, I no longer use tableViews or collectionViews, I use IGListKit. But if I were doing a popup UI like that again, I would be using this[ library instead](https://github.com/IcaliaLabs/Presentr/tree/master/Presentr).
