### ISSUE TITLE
Because of FXBlurView, any view behind the popup that was hidden is shown after the popup is dismissed

### ISSUE THREAD

**Issue by victoraraujo01** [Orderella/PopupDialog#103] opened 2017-02-01 20:53 UTC
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 8.0): 8.2.1
- PopupDialog version (e.g. 0.5.0): 0.5.3
- Minimum deployment target (e.g. 9.0): 10.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 3.0

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.1.0): 1.1.1

## What did you do?

Presented a popup over a view that has a subview hidden  

## What did you expect to happen?

After the popup is dismissed, the view should be exactly as it was before, with the subview hidden.  

## What happened instead?

After the popup is dismissed, the hidden view is being displayed. This is being caused by FXBlurView, see https://github.com/nicklockwood/FXBlurView/issues/126 for more details.

**Comment by mwfire** [comment] 2017-02-02 19:32
Thanks for reporting this, I will look into it asap.

**Comment by mwfire** [comment] 2017-02-04 17:07
I tested this with the example app and followed the links. It seems this bug exists, however I cannot reproduce it. Can you please attach an example project? Thanks!

**Comment by victoraraujo01** [comment] 2017-02-15 21:34
Sorry it took so long, haven't had much time in the last week to take a look at this.

Here's a project reproducing the error. It seems that it's more of an edge case than I thought, very specific to what I had in my project. I only managed to recreate the issue with a hidden UIActivityIndicator inside a Stack View. You can try it out in the project by pressing the "Open popup" button and verifying the the activity indicators in all cells are displayed.

[PopupTest.zip](https://github.com/Orderella/PopupDialog/files/778435/PopupTest.zip)

State before pressing "Open Popup"
![print1](https://cloud.githubusercontent.com/assets/507925/22996386/5c1ec50e-f3ad-11e6-8062-15078024ed12.jpg)

State after pressing "Open Popup"
![print2](https://cloud.githubusercontent.com/assets/507925/22996396/5e295c60-f3ad-11e6-96fc-75f852a3ec9d.jpg)

**Comment by mwfire** [comment] 2017-02-16 16:52
Thanks for the effort @victoraraujo01, I will look at this asap!

**Comment by mwfire** [comment] 2017-02-23 21:44
Ready for testing on develop: `pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => 'development'`

**Comment by terenzeyuen** [comment] 2017-03-10 16:10
Having this issue too.

**Comment by terenzeyuen** [comment] 2017-03-10 16:16
I can confirm development branch fixes it.

**Comment by mwfire** [comment] 2017-03-18 08:33
Released with v. 0.5.4

**Closed as completed by mwfire** 2017-03-18 08:33 UTC
Labels: ready for testing
