### ISSUE TITLE
tableView: didSelectRowAt indexPath method not invoked

### ISSUE THREAD

**Issue by DanhDue** [Orderella/PopupDialog#60] opened 2016-11-07 07:23 UTC
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.

# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): 10.11.5
- Xcode version (e.g. 8.0): 8.0
- PopupDialog version (e.g. 0.5.0): 0.5.0
- Minimum deployment target (e.g. 9.0): 9.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 3.0

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.1.0): 1.1.0

## What did you do?

I Implement UITableView in Dialog's UIViewController, but when i click to item then tableView: didSelectRowAt indexPath method not invoked.

**Comment by mwfire** [comment] 2016-11-08 08:17
Duplicate of #56

**Closed as completed by mwfire** 2016-11-08 08:17 UTC
Labels: duplicate
